In [1]:
pip install ir-datasets

WARNING: The directory '/mnt/primary/launcher-cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: ir-datasets in /opt/miniconda3/lib/python3.10/site-packages (0.5.10)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (4.13.4)
Requirement already satisfied: inscriptis>=2.2.0 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (2.6.0)
Requirement already satisfied: lxml>=4.5.2 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (5.4.0)
Requirement already satisfied: numpy>=1.18.1 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (1.26.4)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (6.0.2)
Requirement already satisfied: requests>=2.22.0 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.38.0 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (4.67.1)
Requirement already satisfied: trec-car-tools>=2.5.4 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (2.6)
Requirement already satisfied: lz4>=3.1.10 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (4.4.4)
Requirement already satisfied: warc3-wet>=0.2.3 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (0.2.5)
Requirement already satisfied: warc3-wet-clueweb09>=0.2.5 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (0.2.5)
Requirement already satisfied: zlib-state>=0.1.3 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (0.1.9)
Requirement already satisfied: ijson>=3.1.3 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (3.4.0)
Requirement already satisfied: unlzw3>=0.2.1 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (0.2.3)
Requirement already satisfied: pyarrow>=16.1.0 in /opt/miniconda3/lib/python3.10/site-packages (from ir-datasets) (20.0.0)
Requirement already satisfied: soupsieve>1.2 in /opt/miniconda3/lib/python3.10/site-packages (from beautifulsoup4>=4.4.1->ir-datasets) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/miniconda3/lib/python3.10/site-packages (from beautifulsoup4>=4.4.1->ir-datasets) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/miniconda3/lib/python3.10/site-packages (from requests>=2.22.0->ir-datasets) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/lib/python3.10/site-packages (from requests>=2.22.0->ir-datasets) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/lib/python3.10/site-packages (from requests>=2.22.0->ir-datasets) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/lib/python3.10/site-packages (from requests>=2.22.0->ir-datasets) (2025.4.26)
Requirement already satisfied: cbor>=1.0.0 in /opt/miniconda3/lib/python3.10/site-packages (from trec-car-tools>=2.5.4->ir-datasets) (1.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pyautocorpus

WARNING: The directory '/mnt/primary/launcher-cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting pyautocorpus
  Downloading pyautocorpus-0.1.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.6 kB)
Downloading pyautocorpus-0.1.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (379 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 379.9/379.9 kB 8.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pyautocorpus
Successfully installed pyautocorpus-0.1.12
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [1]:
import ir_datasets

dataset = ir_datasets.load("trec-fair-2021")

[INFO] acessing TREC Fair Ranking 2021 through trec-fair-2021 is deprecated; use trec-fair/2021 instead.

In [8]:
import pandas as pd
from tqdm import tqdm
corpus_dict = {"docno": [], "title": [], "text": [], "geographic_locations": []}
for doc in tqdm(dataset.docs_iter()):
    doc_id = doc[0]
    title = doc[1]
    article = doc[2]
    geo = doc[6]

    corpus_dict["docno"].append(int(doc_id))
    corpus_dict["text"].append(str(article))
    corpus_dict["title"].append(str(title))
    corpus_dict["geographic_locations"].append(geo)
    
corpus_df = pd.DataFrame(corpus_dict)
corpus_df.to_csv("./trec-2021/trec_corpus.csv", index=False)

6280328it [04:13, 24749.63it/s]

In [9]:
# this cell is to constuct a dataframe which contains two columns query_id and rel_doc_id_list.

import ir_datasets
import pandas as pd

query_rel_dict = dict()

dataset = ir_datasets.load("trec-fair-2021/train")
for i, qrel in enumerate(dataset.qrels_iter()):
    # qrel # namedtuple<query_id, doc_id, relevance, iteration>
    if qrel.relevance==1:
        if qrel.query_id not in query_rel_dict:
            query_rel_dict[qrel.query_id] = []
        query_rel_dict[qrel.query_id].append(qrel.doc_id)

# Convert the dictionary to a list of rows
rows = [{"query_id": k, "rel_doc_id_list": v} for k, v in query_rel_dict.items()]

# Create a DataFrame
qrel_df = pd.DataFrame(rows, columns=["query_id", "rel_doc_id_list"])

# View the DataFrame
print(qrel_df.head())

[INFO] acessing TREC Fair Ranking 2021 through trec-fair-2021/train is deprecated; use trec-fair/2021/train instead.

  query_id                                    rel_doc_id_list
0        1  [572, 627, 903, 1193, 1542, 1634, 3751, 3866, ...
1        2  [682, 954, 1170, 1315, 1322, 1324, 1325, 1435,...
2        3  [5729, 8490, 9623, 10391, 12231, 13791, 16078,...
3        4  [849, 852, 1293, 1902, 1942, 2039, 2075, 2082,...
4        5  [1135, 1136, 1293, 1893, 2129, 2140, 3797, 380...

In [10]:
len(qrel_df)

57

In [15]:
# # this cell is to get id of documents containing less than 250 words.
# import gzip
# import json
# from tqdm import tqdm

# desired_doc_ids = []
# sum_length = 0
# max_body_length_treshold = 512
# min_body_length_treshold = 0
# min_title_length_treshold = 0
# with gzip.open('./trec-2021/trec_corpus.json.gz', 'rt', encoding='utf-8') as f:
#     for line in tqdm(f):
#         doc = json.loads(line)
#         print(doc.keys())
#         break
#         if (len(doc["text"].split()) <= max_body_length_treshold): #(len(doc["plain"].split()) >= min_body_length_treshold) and (len(doc["title"].split()) >= min_title_length_treshold)
#             sum_length += len(doc["text"].split())
#             desired_doc_ids.append(int(doc["id"]))

#         # desired_doc_ids.append(doc["id"])
# this cell is to get id of documents containing less than 250 words.
from tqdm import tqdm
import pandas as pd

desired_doc_ids = []
sum_length = 0
max_body_length_treshold = 512
min_body_length_treshold = 0
min_title_length_treshold = 0
# corpus_df = pd.read_csv("./trec-2021/trec_corpus.csv")
for eachrow in tqdm(corpus_df.itertuples(index=False)):
    article = eachrow.text
    doc_id = eachrow.docno
    article_len = len(article.split())
    if article_len <= max_body_length_treshold: #(len(doc["plain"].split()) >= min_body_length_treshold) and (len(doc["title"].split()) >= min_title_length_treshold)
        sum_length += article_len
        desired_doc_ids.append(int(doc_id))

6280328it [01:23, 75015.81it/s]

In [16]:
len(desired_doc_ids), sum_length/len(desired_doc_ids)

(4905140, 156.4988387691279)

In [17]:
for i in desired_doc_ids:
    print(type(i))
    break

<class 'int'>

In [18]:
# This cell is to filter out documents not being the list of desired doc ids.
import gzip
import json
from tqdm import tqdm

desired_doc_ids_set = set(desired_doc_ids)  # ensures fast lookup
filtered_desired_doc_ids = []

with gzip.open('./trec-2021/trec_metadata.json.gz', 'rt', encoding='utf-8') as f:
    for line in tqdm(f, desc="Filtering docs"):
        data = json.loads(line)
        # print(data.keys())
        # print(data["geographic_locations"])
        if (int(data["page_id"]) in desired_doc_ids_set) and (data["geographic_locations"] != ""):
            filtered_desired_doc_ids.append(data["page_id"])

Filtering docs: 6023428it [00:13, 448132.91it/s]

In [19]:
len(filtered_desired_doc_ids)

4692610

In [20]:
with open("./trec-2021/filtered_desired_doc_ids.txt", "w") as f:
    for doc_id in filtered_desired_doc_ids:
        f.write(str(doc_id) + "\n")

In [21]:
filtered_desired_doc_ids = []
with open("./trec-2021/filtered_desired_doc_ids.txt", "r") as f:
    for line in f:
        filtered_desired_doc_ids.append(int(line.strip()))

In [22]:
# Ensure your list of desired IDs is a set for faster lookup
filtered_desired_doc_ids_set = set(filtered_desired_doc_ids)
def selected_docs(row):
    selected_docs_list = []
    for doc_id in row["rel_doc_id_list"]:
        if int(doc_id) in filtered_desired_doc_ids_set:
            selected_docs_list.append(int(doc_id))
    return selected_docs_list

# Create a new column to count how many relevant documents per query are in desired_id_set
qrel_df["selected_docs_list"] = qrel_df.apply(selected_docs, axis=1)

# Optionally: preview the result
print(qrel_df[["query_id", "selected_docs_list"]].head())

  query_id                                 selected_docs_list
0        1  [36834, 42646, 45847, 49396, 55751, 56122, 623...
1        2  [1873, 5970, 6298, 7118, 12483, 12821, 13773, ...
2        3  [16546, 22104, 22355, 22356, 31477, 49132, 598...
3        4  [13463, 14315, 15365, 15536, 16941, 17869, 200...
4        5  [1136, 3800, 3805, 3814, 3851, 28416, 37221, 4...

In [23]:
# Ensure your list of desired IDs is a set for faster lookup
def count_docs(row):
    return len(row["selected_docs_list"])

# Create a new column to count how many relevant documents per query are in desired_id_set
qrel_df["desired_doc_count"] = qrel_df.apply(count_docs, axis=1)

In [24]:
qrel_df

,query_id,rel_doc_id_list,selected_docs_list,desired_doc_count
0,1,"[572, 627, 903, 1193, 1542, 1634, 3751, 3866, ...","[36834, 42646, 45847, 49396, 55751, 56122, 623...",4217
1,2,"[682, 954, 1170, 1315, 1322, 1324, 1325, 1435,...","[1873, 5970, 6298, 7118, 12483, 12821, 13773, ...",42915
2,3,"[5729, 8490, 9623, 10391, 12231, 13791, 16078,...","[16546, 22104, 22355, 22356, 31477, 49132, 598...",50928
3,4,"[849, 852, 1293, 1902, 1942, 2039, 2075, 2082,...","[13463, 14315, 15365, 15536, 16941, 17869, 200...",36472
4,5,"[1135, 1136, 1293, 1893, 2129, 2140, 3797, 380...","[1136, 3800, 3805, 3814, 3851, 28416, 37221, 4...",34002
5,6,"[308, 340, 700, 728, 736, 784, 851, 852, 892, ...","[340, 892, 910, 1563, 1654, 1751, 1763, 1873, ...",65343
6,7,"[595, 890, 1020, 1135, 1293, 1806, 1893, 2575,...","[10620, 12556, 16546, 22104, 30097, 31477, 367...",495556
7,8,"[344, 676, 808, 872, 1247, 1806, 1828, 2083, 2...","[2723, 3785, 6337, 7033, 8079, 8436, 10275, 13...",52379
8,9,"[4243, 17163, 25506, 39027, 45360, 45772, 4811...","[69190, 80142, 84775, 87963, 90653, 96901, 106...",10202
9,10,"[1017, 1178, 1239, 1669, 1735, 2642, 2784, 284...","[1669, 8676, 60347, 94782, 99570, 100099, 1002...",2979
10,11,"[1081, 1581, 1806, 1893, 1938, 2391, 2593, 259...","[4797, 5420, 11516, 14543, 16791, 20040, 23896...",14969
11,12,"[1235, 5981, 12233, 15908, 15912, 15915, 17962...","[70453, 72096, 72539, 74972, 77404, 77408, 149...",11040
12,13,"[1020, 2812, 3401, 3986, 5134, 10474, 11146, 1...","[49070, 65765, 68385, 75682, 130919, 150382, 1...",4805
13,14,"[332, 924, 1152, 1500, 1975, 2890, 4481, 4653,...","[332, 5743, 11312, 31261, 37366, 45250, 54835,...",9080
14,15,"[1425, 1700, 2241, 2313, 2363, 2406, 4527, 622...","[1700, 6650, 8299, 12472, 12797, 16206, 19369,...",7234
15,16,"[742, 775, 1164, 1242, 1368, 1451, 1453, 1456,...","[742, 2925, 6132, 6212, 6867, 7030, 9313, 1201...",2295
16,17,"[1132, 4109, 4367, 7239, 11040, 12501, 13961, ...","[18148, 18544, 22794, 144088, 207548, 216386, ...",40347
17,18,"[3973, 4960, 5693, 5931, 11513, 18724, 20601, ...","[20601, 30614, 38843, 39112, 39838, 68000, 689...",23785
18,19,"[1425, 1428, 4527, 4763, 6226, 6260, 8520, 870...","[37715, 38405, 61611, 87880, 92883, 96564, 985...",2012
19,20,"[25, 653, 876, 1338, 2088, 2992, 3600, 3933, 4...","[4589, 23254, 31257, 45955, 55937, 101718, 168...",2519
20,21,"[1146, 2082, 2428, 2753, 2819, 3233, 4318, 452...","[7838, 9251, 9546, 9828, 10887, 11774, 26132, ...",2917
21,22,"[10893, 38352, 52892, 67999, 219523, 219834, 2...","[67999, 219523, 219834, 225810, 234244, 309385...",5198
22,23,"[925, 2174, 2273, 2289, 2358, 3165, 4224, 4392...","[8649, 10830, 11052, 30097, 44237, 45316, 5226...",248721
23,24,"[783, 802, 842, 854, 874, 1527, 1528, 1529, 15...","[2826, 3234, 9011, 10727, 12798, 13463, 17743,...",4328
24,25,"[6749, 12422, 12551, 18090, 31500, 47319, 4732...","[12422, 67994, 73083, 73786, 181181, 219550, 2...",5895
25,26,"[765, 1950, 2006, 2547, 2784, 2786, 2834, 2847...","[10905, 23531, 36566, 53487, 103170, 144226, 1...",2198
26,27,"[1446, 2907, 6710, 7478, 8769, 14098, 15080, 1...","[2907, 49054, 54384, 54397, 54583, 65959, 7623...",2264
27,28,"[872, 3092, 10125, 10126, 10130, 10287, 10415,...","[10418, 10441, 10445, 10457, 10460, 10462, 104...",13121
28,29,"[736, 1078, 1389, 2006, 2187, 2632, 2741, 3875...","[17427, 34468, 35254, 59042, 68544, 68590, 688...",2284
29,30,"[983, 1235, 2707, 2868, 3003, 3838, 3963, 3965...","[2707, 4182, 4195, 16568, 18546, 22412, 27846,...",20850
30,31,"[640, 642, 643, 649, 691, 766, 794, 795, 1338,...","[642, 766, 794, 2381, 2654, 2719, 4195, 4819, ...",20753
31,32,"[864, 1017, 1177, 1208, 2126, 4188, 4631, 5015...","[89654, 142698, 165189, 218030, 264565, 284906...",1554
32,33,"[1581, 1605, 1938, 4580, 4842, 5278, 6310, 688...","[1605, 24519, 25727, 27161, 49528, 83306, 8671...",4627
33,34,"[308, 677, 740, 803, 1164, 1171, 1241, 1361, 1...","[6212, 6331, 6867, 8437, 8648, 11676, 11964, 1...",4384
34,35,"[914, 1203, 1361, 1837, 2179, 2210, 2447, 2999...","[9574, 12296, 23036, 43822, 48586, 51052, 5210...",6562
35,36,"[25, 653, 674, 765, 782, 876, 897, 922, 967, 9...","[1303, 4516, 6105, 7435, 8885, 9665, 11806, 13...",21866
36,37,"[841, 844, 868, 1078, 1130, 1360, 1373, 1408, ...","[841, 1373, 1553, 1683, 1702, 1873, 1880, 2552...",11054
37,38,"[24245, 169660, 169662, 175552, 204196, 207083...","[883115, 900244, 1343841, 1368872, 1709798, 24...",2597
38,39,"[2942, 2950, 2999, 3010, 3032, 3740, 3741, 718...","[53979, 60173, 142047, 181181, 200791, 207014,...",1640
39,40,"[690, 844, 1988, 2162, 2273, 2289, 2758, 2938,...","[2162, 2938, 8649, 10003, 11463, 14067, 18278,...",22190
40,41,"[595, 844, 890, 1216, 3138, 3354, 4405, 4443, ...","[5038, 15495, 16546, 22104, 22355, 22356, 2236...",149455
41,42,"[1495, 4059, 5034, 12369, 13076, 14987, 17387,...","[18129, 18325, 39264, 55759, 55766, 76299, 833...",4199
42,43,"[1020, 5698, 5766, 7160, 15058, 18476, 21453, ...","[7160, 22990, 22993, 51722, 152505, 163121, 17...",2730
43,44,"[864, 2083, 4158, 6585, 6751, 8367, 8487, 9779...","[4158, 11433, 22995, 65924, 70597, 81290, 1016...",3711
44,45,"[1017, 1542, 1577, 1637, 1638, 1880, 2427, 294...","[1637, 1638, 1880, 7066, 8785, 9684, 10078, 14...",8292
45,46,"[12, 307, 308, 339, 665, 691, 705, 710, 771, 7...","[710, 3533, 3620, 3665, 3702, 5436, 5456, 5467...",38850
46,47,"[3735, 7954, 9130, 13137, 13820, 15616, 15839,...","[22995, 30514, 85578, 147736, 148377, 157601, ...",2679
47,48,"[25055, 86701, 202424, 207333, 242464, 244335,...","[563905, 671279, 696461, 752697, 844288, 84606...",3205
48,49,"[13755, 15077, 25736, 54522, 64054, 94255, 146...","[190408, 219569, 228654, 370240, 400230, 50033...",8095
49,50,"[1208, 5729, 10391, 16078, 16546, 17190, 18084...","[16546, 22104, 49132, 59896, 67287, 67291, 675...",17603
50,51,"[4405, 5399, 6721, 8508, 28262, 28478, 28489, ...","[40048, 40381, 71557, 82370, 108421, 108519, 1...",7344
51,52,"[597, 1494, 2847, 3253, 3262, 3466, 3658, 3661...","[3658, 3665, 17758, 17760, 17761, 65452, 84841...",5544
52,53,"[4550, 5667, 8402, 9118, 16558, 27998, 27999, ...","[47311, 54216, 67986, 81241, 101211, 181181, 2...",21941
53,54,"[1948, 2032, 2139, 2372, 2393, 2861, 3214, 337...","[2139, 2372, 7033, 8425, 14575, 23875, 27075, ...",53574
54,55,"[1354, 1750, 2627, 2926, 3226, 3460, 4917, 571...","[19250, 21040, 30393, 44296, 54930, 90306, 924...",3073
55,56,"[890, 974, 984, 2126, 2144, 2519, 2529, 2847, ...","[14575, 18684, 22104, 22995, 31477, 40384, 403...",50033
56,57,"[17270, 21383, 21385, 21387, 21388, 21389, 213...","[169822, 317815, 359471, 381683, 408992, 41709...",7146

In [25]:
top_3 = qrel_df.nlargest(3, 'desired_doc_count')
top_val = qrel_df['desired_doc_count'].nlargest(3).min()
qrel_df = qrel_df[qrel_df['desired_doc_count'] >= top_val]

In [26]:
qrel_df

,query_id,rel_doc_id_list,selected_docs_list,desired_doc_count
6,7,"[595, 890, 1020, 1135, 1293, 1806, 1893, 2575,...","[10620, 12556, 16546, 22104, 30097, 31477, 367...",495556
22,23,"[925, 2174, 2273, 2289, 2358, 3165, 4224, 4392...","[8649, 10830, 11052, 30097, 44237, 45316, 5226...",248721
40,41,"[595, 844, 890, 1216, 3138, 3354, 4405, 4443, ...","[5038, 15495, 16546, 22104, 22355, 22356, 2236...",149455

In [27]:
import ir_datasets
dataset = ir_datasets.load("trec-fair-2021/train")
for query in dataset.queries_iter():
    if query[0] in qrel_df["query_id"].tolist(): # namedtuple<query_id, text, url>
      print(query)

FairTrecQuery(query_id='7', text='Biography/sports and games work group', keywords=['sports biography', 'athlets', 'player', 'memoir', 'refree', 'coach'], scope='The Sports and Games Work Group is a working group of members of the Biography WikiProject dedicated to ensuring quality and coverage of biography articles.', homepage='https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Biography/Sports_and_games')
FairTrecQuery(query_id='23', text='Football', keywords=['football', 'soccer', 'team', 'club', 'league', 'season', 'championship', 'match', 'player', 'stadium', 'pitch'], scope='Any article relating to association football (soccer) for example including football clubs, national teams, national associations, competitions, leagues, seasons, matches, players, stadiums and governing bodies such as FIFA and UEFA.', homepage='https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Football')
FairTrecQuery(query_id='41', text='Olympics', keywords=['olympic games', 'paralympics', 'olympic medalists'], scope='Any article relating to the olympics, paralympics, or deaflympics.', homepage='https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Olympics')

[INFO] acessing TREC Fair Ranking 2021 through trec-fair-2021/train is deprecated; use trec-fair/2021/train instead.

In [32]:
final_chosen_documents = set()
for l in qrel_df["selected_docs_list"].tolist():
    final_chosen_documents.update(set(l))

In [33]:
len(final_chosen_documents)

604013

In [34]:
import gzip
import json
import pandas as pd
from tqdm import tqdm

rows = []
investigated_documents = set()
with gzip.open('./trec-2021/trec_metadata.json.gz', 'rt', encoding='utf-8') as f:
    for line in tqdm(f, desc="Filtering docs"):
        data = json.loads(line)
        if int(data["page_id"]) in final_chosen_documents:
            if int(data["page_id"]) in investigated_documents:
                continue
            investigated_documents.add(int(data["page_id"]))
            if data["geographic_locations"] == []:
                geographic_locations = ["None"]
            else:
                geographic_locations = data["geographic_locations"]
            rows.append({
                "docno": int(data["page_id"]),
                "geographic_locations": geographic_locations,
            })
# Create DataFrame once
document_features = pd.DataFrame(rows)

Filtering docs: 6023428it [00:13, 434051.04it/s]

In [35]:
len(document_features)

604013

In [36]:
all_geographic_locations = set()
unique_geographic_location_lists = set()
for geographic_locations in document_features['geographic_locations'].tolist():
    all_geographic_locations.update(set(geographic_locations))
    unique_geographic_location_lists.add(str(geographic_locations))

In [37]:
len(all_geographic_locations), all_geographic_locations

(7,
 {'Africa',
  'Asia',
  'Europe',
  'Latin America and the Caribbean',
  'None',
  'Northern America',
  'Oceania'})

In [30]:
len(unique_geographic_location_lists), unique_geographic_location_lists

(31,
 {"['Africa']",
  "['Asia', 'Africa']",
  "['Asia', 'Europe', 'Africa']",
  "['Asia', 'Europe', 'Northern America']",
  "['Asia', 'Europe']",
  "['Asia', 'Northern America']",
  "['Asia']",
  "['Europe', 'Africa']",
  "['Europe']",
  "['Latin America and the Caribbean', 'Africa']",
  "['Latin America and the Caribbean', 'Asia', 'Europe']",
  "['Latin America and the Caribbean', 'Asia', 'Northern America']",
  "['Latin America and the Caribbean', 'Asia']",
  "['Latin America and the Caribbean', 'Europe']",
  "['Latin America and the Caribbean', 'Northern America', 'Europe']",
  "['Latin America and the Caribbean', 'Northern America']",
  "['Latin America and the Caribbean', 'Oceania']",
  "['Latin America and the Caribbean']",
  "['None']",
  "['Northern America', 'Africa']",
  "['Northern America', 'Asia']",
  "['Northern America', 'Europe', 'Asia']",
  "['Northern America', 'Europe']",
  "['Northern America']",
  "['Oceania', 'Africa']",
  "['Oceania', 'Asia', 'Europe']",
  "['Oceania', 'Asia', 'Northern America']",
  "['Oceania', 'Asia']",
  "['Oceania', 'Europe']",
  "['Oceania', 'Northern America']",
  "['Oceania']"})

In [38]:
import ast
geo_counter = dict()
for str_list in unique_geographic_location_lists:
    geo_list = ast.literal_eval(str_list)
    for geo in geo_list:
        if geo in geo_counter:
            geo_counter[geo] += 1
            continue
        geo_counter[geo] = 1
geo_counter

{'Oceania': 11,
 'Asia': 17,
 'Europe': 17,
 'Africa': 8,
 'Northern America': 18,
 'Latin America and the Caribbean': 12,
 'None': 1}

In [39]:
import ast
def calucluate_represnetative_per_combination(unique_geographic_location_lists): 
    geo_counter = dict()
    for str_list in unique_geographic_location_lists:
        geo_list = ast.literal_eval(str_list)
        for geo in geo_list:
            if geo in geo_counter:
                geo_counter[geo] += 1
                continue
            geo_counter[geo] = 1

    max_value = max(geo_counter.values())
    geo_counter = {k: max_value-(v-1) for k, v in geo_counter.items()}
    return geo_counter

In [40]:
import ast

def select_one_row_per_combination_fast(df, final_df):
    selected_rows = []

    # Create a set of hashes for rows in final_df to check for duplicates efficiently
    existing_hashes = set(final_df.astype(str).apply(lambda row: hash(tuple(row)), axis=1))

    df['geographic_locations_str'] = df['geographic_locations'].apply(lambda x: str(x))
    category_columns = ['geographic_locations_str']
    grouped = df.groupby(category_columns, sort=False)
    unique_geographic_location_lists = []
    for geographic_locations_str, group in grouped:
        # print(type(geographic_locations_str[0]))
        unique_geographic_location_lists.append(geographic_locations_str[0])
    # print(unique_geographic_location_lists)
    geo_dict = calucluate_represnetative_per_combination(unique_geographic_location_lists)
    
    for geographic_locations_str, group in grouped:
        # Shuffle rows in group (you can set random_state if you want reproducibility)
        group_shuffled = group.sample(frac=1, random_state=42)

        # Try each row until we find one not in final_df
        if len(ast.literal_eval(geographic_locations_str[0])) == 1:
            # print(ast.literal_eval(geographic_locations_str[0]))
            number_of_representatives = geo_dict[ast.literal_eval(geographic_locations_str[0])[0]]
            # print(number_of_representatives)
            # print(len(group_shuffled))
        else:
            number_of_representatives = 1

        selected_counter = 0 
        for _, row in group_shuffled.iterrows():
            row_hash = hash(tuple(row.astype(str)))
            # if row_hash not in existing_hashes:
            selected_rows.append(row)
            # existing_hashes.add(row_hash)
            selected_counter += 1
            if selected_counter == number_of_representatives:
                break
    # Return the selected rows as a DataFrame
    return pd.DataFrame(selected_rows)

In [41]:
final_df = pd.DataFrame()  # Initialize an empty DataFrame to collect results
count = 0
for eachrow in qrel_df.itertuples(index=False):
    selected_docs_list = eachrow.selected_docs_list
    print(count)
    filtered_df = document_features[document_features['docno'].isin(selected_docs_list)]
    selected_df = select_one_row_per_combination_fast(filtered_df, final_df)
    print(f"Selected {len(selected_df)} rows.")
    
    all_geographic_locations = set()
    geo_counter = dict()
    for geographic_locations in selected_df['geographic_locations'].tolist():
        for geo_location in geographic_locations:
            if geo_location in geo_counter:
                geo_counter[geo_location] += 1
                continue
            geo_counter[geo_location] = 1
    print(geo_counter)
    print("***********************")
    selected_df.to_csv(f"./trec-2021/query_ids_{eachrow.query_id}.csv", index=False)
    # print(selected_df.head())
    final_df = pd.concat([final_df, selected_df], ignore_index=True)
    count += 1

0

/tmp/ipykernel_366/864522898.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['geographic_locations_str'] = df['geographic_locations'].apply(lambda x: str(x))

Selected 80 rows.
{'None': 18, 'Northern America': 18, 'Africa': 18, 'Europe': 18, 'Asia': 18, 'Oceania': 18, 'Latin America and the Caribbean': 18}
***********************
1

/tmp/ipykernel_366/864522898.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['geographic_locations_str'] = df['geographic_locations'].apply(lambda x: str(x))
/tmp/ipykernel_366/864522898.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['geographic_locations_str'] = df['geographic_locations'].apply(lambda x: str(x))

Selected 52 rows.
{'Europe': 12, 'None': 12, 'Latin America and the Caribbean': 12, 'Africa': 12, 'Northern America': 12, 'Asia': 12, 'Oceania': 12}
***********************
2
Selected 66 rows.
{'None': 14, 'Africa': 14, 'Europe': 14, 'Northern America': 14, 'Asia': 14, 'Oceania': 14, 'Latin America and the Caribbean': 14}
***********************

In [42]:
import gzip
import json
from tqdm import tqdm
import pandas as pd

corpus_dict = {"docno": [], "title": [], "text": []}
with gzip.open('./trec-2021/trec_corpus.json.gz', 'rt', encoding='utf-8') as f:
    for line in tqdm(f):
        doc = json.loads(line)
        if int(doc["id"]) in final_chosen_documents:
              corpus_dict["docno"].append(int(doc["id"]))
              corpus_dict["text"].append(doc["text"])
              corpus_dict["title"].append(doc["title"])

corpus_df = pd.DataFrame(corpus_dict)
corpus_df.to_csv("./trec-2021/corpus.csv", index=False)

6280328it [06:28, 16164.75it/s]

In [43]:
document_features.to_csv("./trec-2021/document_features.csv", index=False)